### ISSUE TITLE
Not able to register new user

### ISSUE THREAD

**Issue by thomsonimjd** [JincorTech/backend-ico-dashboard#194]
I get the below error when new user gets registered, so it's a internal server error as a result.

``2018-12-30T10:47:55.469Z - error: [VERIFICATION_CLIENT] Throwed exception: Initiate Error: getaddrinfo ENOTFOUND verify verify:3000
    at Request.request [as _callback] (/home/aequalis/Documents/thomson/coldwallet/backend-ico-dashboard/node_modules/web-request/index.js:61:24)
    at self.callback (/home/aequalis/Documents/thomson/coldwallet/backend-ico-dashboard/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at Request.onRequestError (/home/aequalis/Documents/thomson/coldwallet/backend-ico-dashboard/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:180:13)
    at ClientRequest.emit (domain.js:422:20)
    at Socket.socketErrorListener (_http_client.js:395:9)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:422:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
getaddrinfo ENOTFOUND verify verify:3000
Error: getaddrinfo ENOTFOUND verify verify:3000
    at Request.request [as _callback] (/home/aequalis/Documents/thomson/coldwallet/backend-ico-dashboard/node_modules/web-request/index.js:61:24)
    at self.callback (/home/aequalis/Documents/thomson/coldwallet/backend-ico-dashboard/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at Request.onRequestError (/home/aequalis/Documents/thomson/coldwallet/backend-ico-dashboard/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:180:13)
    at ClientRequest.emit (domain.js:422:20)
    at Socket.socketErrorListener (_http_client.js:395:9)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:422:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
::1 - - [30/Dec/2018:10:47:55 +0000] "POST /user HTTP/1.1" 500 31 "-" "PostmanRuntime/7.1.1"
``

**Comment by hlogeon** [comment]
You didn't run verify server. What is required in order to run backend module.
Check out your docker-compose settings and make sure you have verify server there
