### ISSUE TITLE
 Service 'ico' failed to build: The command '/bin/sh -c chmod 755 /usr/local/bin/custom-entrypoint.sh &&     addgroup ico &&     adduser -D -G ico ico &&     apk add --update --no-cache git python make g++ curl grep bash &&     npm i -g yarn &&     yarn install' returned a non-zero code: 1 ubuntu@ ~/Desktop/bac

### ISSUE THREAD

**Issue by bogdyak** [JincorTech/backend-ico-dashboard#197]
When i am trying ` sudo docker-compose build --no-cache`

Having this issue

```
make: *** [sha3.target.mk:99: Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/usr/src/app/node_modules/sha3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/sha3
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by hlogeon** [comment]
Hello! What OS did you use?
